import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/budget.css',
                'resources/css/dbadmin.css',
                'resources/css/forgot.css',
                'resources/css/header.css',
                'resources/css/infoman.css',
                'resources/css/inventory.css',
                'resources/css/login.css',
                'resources/css/messages.css',
                'resources/css/price.css',
                'resources/css/projectapp.css',
                'resources/css/projectreq.css',
                'resources/css/signup.css',
                'resources/css/supprankings.css',
                'resources/css/app-layout-custom.css',
                'resources/css/contracts-editor.css',
                'resources/css/project-timeline-show.css',
                'resources/css/landing-catalogue.css',
                'resources/js/app.js',
                'resources/js/bootstrap.js',
                'resources/js/budget.js',
                'resources/js/header.js',
                'resources/js/import-alerts.js',
                'resources/js/info-man.js',
                'resources/js/inventory.js',
                'resources/js/login.js',
                'resources/js/price.js',
                'resources/js/projectreq.js',
                'resources/js/signup-alert.js',
                'resources/js/supprankings.js',
                'resources/js/contracts-editor.js',
                'resources/js/messages-show.js',
                'resources/js/project-timeline-show.js',
                'resources/js/landing-catalogue.js',
                'resources/css/manager-dashboard.css',
                'resources/css/price-analysis.css',
                'resources/js/price-analysis.js',
                'resources/css/materials-form.css',
                'resources/js/materials-form.js',
                'resources/css/quotations-form.css',
                'resources/js/quotations-form.js',
                'resources/css/warehouse-dashboard.css',
                'resources/js/warehouse-dashboard.js',
                'resources/css/client-dashboard.css',
                'resources/css/procurement-dashboard-main.css',
                'resources/js/procurement-dashboard-main.js',
                'resources/css/procurement-analytics-dashboard.css',
                'resources/css/finance-dashboard.css',
                'resources/css/supplier-dashboard.css',
                'resources/js/supplier-dashboard.js',
                'resources/css/messages-index.css',
                'resources/js/messages-index.js',
                'resources/css/payments-index.css',
                'resources/js/payments-index.js',
                'resources/css/projects-index.css',
                'resources/js/projects-index.js',
                'resources/css/admin-purchase-requests-form.css',
                'resources/js/admin-purchase-requests-form.js',
                'resources/css/admin-analytics-dashboard.css',
                'resources/css/admin-transactions.css',
                'resources/css/admin-suppliers.css',
                'resources/css/admin-purchase-orders.css',
            ],
            refresh: true,
        }),
    ],
    build: {
        outDir: 'public/build',
        assetsDir: 'assets',
        manifest: true,
        minify: 'esbuild',
        sourcemap: false,
    },
    server: {
        hmr: {
            host: 'localhost',
        },
    },
});
