import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/app.css',
                'resources/css/budget.css',
                'resources/css/dbadmin.css',
                'resources/css/forgot.css',
                'resources/css/header.css',
                'resources/css/infoman.css',
                'resources/css/inventory.css',
                'resources/css/login.css',
                'resources/css/messages.css',
                'resources/css/price.css',
                'resources/css/projectapp.css',
                'resources/css/projectreq.css',
                'resources/css/signup.css',
                'resources/css/supprankings.css',
                'resources/css/app-layout.css',
                'resources/js/app-layout.js',
                'resources/css/messages-index.css',
                'resources/js/messages-index.js',
                'resources/css/contracts-show.css',
                'resources/js/contracts-show.js',
                'resources/css/project-timeline-index.css',
                'resources/js/project-timeline-index.js',
                'resources/css/warehouse-dashboard.css',
                'resources/js/warehouse-dashboard.js',
                'resources/css/supplier-dashboard.css',
                'resources/js/supplier-dashboard.js',
                'resources/js/app.js',
                'resources/js/bootstrap.js',
                'resources/js/budget.js',
                'resources/js/header.js',
                'resources/js/import-alerts.js',
                'resources/js/info-man.js',
                'resources/js/inventory.js',
                'resources/js/login.js',
                'resources/js/price.js',
                'resources/js/projectreq.js',
                'resources/js/signup-alert.js',
                'resources/js/supprankings.js',
                'resources/css/auth-register.css',
                'resources/css/projects-create.css',
                'resources/js/projects-create.js',
                'resources/css/admin-contracts-editor.css',
                'resources/js/admin-contracts-editor.js',
                'resources/css/landing/catalogue.css',
                'resources/js/landing-catalogue.js',
                'resources/css/components-search-select.css',
                'resources/js/components-search-select.js',
                'resources/css/admin-inquiries-form.css',
                'resources/js/admin-inquiries-form.js',
                'resources/css/admin-materials-form.css',
                'resources/js/admin-materials-form.js',
                'resources/js/admin-price-analysis.js',
                'resources/css/admin/quotations/form.css',
                'resources/js/admin/quotations/form.js',
                'resources/css/admin/suppliers/general-recommendation.css',
                'resources/js/admin/suppliers/general-recommendation.js',
                'resources/css/procurement/suppliers-rankings.css',
                'resources/js/procurement/suppliers-rankings.js',
                'resources/css/admin/suppliers/rankings.css',
                'resources/js/admin/suppliers/rankings.js',
                'resources/css/client/quotation/create.css',
                'resources/css/messages/show.css',
                //'resources/js/messages/show.js',
                'resources/css/procurement/analytics/price-analysis.css',
                'resources/js/procurement/analytics/price-analysis.js',
                'resources/css/project-timeline/show.css',
                'resources/css/manager-dashboard.css',
                //'resources/js/project-timeline/show.js',
                //'resources/css/supplier/quotation-respond.css',
                //'resources/js/supplier/quotation-respond.js',
                'resources/css/admin/budget-allocation.css',
                'resources/js/admin/budget-allocation.js',
            ],
            refresh: true,
        }),
    ],
    base: '/build/',
    build: {
        outDir: 'public/build', // Explicit output path
        emptyOutDir: true, 
        rollupOptions: {
            external: ['jquery', 'select2'],
            output: {
                globals: {
                    jquery: '$',
                    select2: 'select2'
                }
            }
        }
    },    // Clears the directory on rebuild
});
