<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Warehouse Analytics Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 13px; color: #222; }
        h1, h2, h3 { color: #1b5e20; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th, td { border: 1px solid #bbb; padding: 6px 10px; text-align: left; }
        th { background: #e8f5e9; }
        .section { margin-bottom: 32px; }
    </style>
</head>
<body>
    <h1>Warehouse Analytics Report</h1>
    <p>Generated: {{ now()->format('F j, Y H:i') }}</p>

    <div class="section">
        <h2>Current Inventory Levels</h2>
        <table>
            <thead>
                <tr>
                    <th>Material</th>
                    <th>Category</th>
                    <th>Current Stock</th>
                </tr>
            </thead>
            <tbody>
                @foreach($materials as $material)
                <tr>
                    <td>{{ $material->name }}</td>
                    <td>{{ $material->category->name ?? '-' }}</td>
                    <td>{{ $material->current_stock }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Most Used Materials per Project</h2>
        <table>
            <thead>
                <tr>
                    <th>Project/Reference</th>
                    <th>Material</th>
                    <th>Total Used</th>
                </tr>
            </thead>
            <tbody>
                @foreach($mostUsedByProject as $row)
                <tr>
                    <td>{{ $row->reference_number }}</td>
                    <td>{{ $row->material->name ?? 'Unknown' }}</td>
                    <td>{{ $row->total_used }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="section">
        <h2>Monthly Usage Trends</h2>
        <table>
            <thead>
                <tr>
                    <th>Year-Month</th>
                    <th>Material</th>
                    <th>Total Used</th>
                </tr>
            </thead>
            <tbody>
                @foreach($monthlyTrends as $row)
                <tr>
                    <td>{{ $row->year }}-{{ str_pad($row->month, 2, '0', STR_PAD_LEFT) }}</td>
                    <td>{{ $row->material->name ?? 'Unknown' }}</td>
                    <td>{{ $row->total_used }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <p style="color:#888; font-size:12px;">This report was generated by SurePrice System.</p>
</body>
</html> 