@extends('layouts.app')

@section('content')
<div class="container py-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="h3 mb-0">Warehouse Reports</h1>
    </div>

    <div class="row">
        <!-- Inventory Report Card -->
        <div class="col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Inventory Report</h5>
                    <p class="card-text text-muted">Generate detailed inventory reports including stock levels, low stock items, and stock movements.</p>
                    <div class="mt-4">
                        <a href="{{ route('warehouse.reports.inventory') }}" class="btn btn-primary">Generate Report</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Stock Movement Report Card -->
        <div class="col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Stock Movement Report</h5>
                    <p class="card-text text-muted">Track all stock movements including incoming and outgoing deliveries, adjustments, and returns.</p>
                    <div class="mt-4">
                        <a href="{{ route('warehouse.reports.movements') }}" class="btn btn-primary">Generate Report</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Delivery Report Card -->
        <div class="col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Delivery Report</h5>
                    <p class="card-text text-muted">View delivery statistics, on-time delivery rates, and delivery performance metrics.</p>
                    <div class="mt-4">
                        <a href="{{ route('warehouse.reports.deliveries') }}" class="btn btn-primary">Generate Report</a>
                    </div>
                </div>
            </div>
        </div>

        <!-- Material Usage Report Card -->
        <div class="col-md-6 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <h5 class="card-title">Material Usage Report</h5>
                    <p class="card-text text-muted">Analyze material usage patterns, popular items, and consumption trends.</p>
                    <div class="mt-4">
                        <a href="{{ route('warehouse.reports.usage') }}" class="btn btn-primary">Generate Report</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Recent Reports -->
    <div class="card">
        <div class="card-header bg-white py-3">
            <h5 class="mb-0">Recent Reports</h5>
        </div>
        <div class="table-responsive">
            <table class="table table-hover mb-0">
                <thead>
                    <tr>
                        <th>Report Type</th>
                        <th>Generated By</th>
                        <th>Date</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($recentReports as $report)
                    <tr>
                        <td>{{ $report->type }}</td>
                        <td>{{ $report->generated_by->name }}</td>
                        <td>{{ $report->created_at->format('M d, Y H:i') }}</td>
                        <td>
                            <a href="{{ route('warehouse.reports.download', $report) }}" class="btn btn-sm btn-primary">Download</a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" class="text-center text-muted">No recent reports found</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection 