<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Inventory Report</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 13px; color: #222; margin: 0; padding: 0; }
        h1 { color: #1b5e20; font-size: 2rem; margin-bottom: 0.5rem; }
        .header { margin-bottom: 24px; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; }
        .meta { color: #888; font-size: 0.95rem; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        th, td { border: 1px solid #bbb; padding: 7px 10px; text-align: left; }
        th { background: #e8f5e9; font-weight: bold; }
        tr:nth-child(even) { background: #f6f6f6; }
        .footer { color: #888; font-size: 0.95rem; text-align: right; margin-top: 32px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Inventory Report</h1>
        <div class="meta">Generated: {{ now()->format('F j, Y H:i') }}</div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Material</th>
                <th>Category</th>
                <th>Current Stock</th>
                <th>Minimum Stock</th>
            </tr>
        </thead>
        <tbody>
            @foreach($materials as $material)
            <tr>
                <td>{{ $material->name }}</td>
                <td>{{ $material->category->name ?? '-' }}</td>
                <td>{{ $material->current_stock }}</td>
                <td>{{ $material->minimum_stock }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <div class="footer">
        This report was generated by SurePrice System.
    </div>
</body>
</html> 